#!/bin/bash
cd "${0%/*}" || exit 1

# Clean src
(cd src && ./Allwclean)

# Clean applications
(cd applications && ./Allwclean)

# Clean all tutorials
(cd tutorials && ./Allclean)

echo; echo "Removing all log.Allwmake build logs"; echo
find . -name log.Allwmake -exec rm -f {} +

#------------------------------------------------------------------------------
