#!/bin/bash
cd "${0%/*}" || exit 1

set -e
set -o pipefail

# Check if OpenFOAM/FOAM has been sourced
if [[ -z "${WM_PROJECT}" ]]
then
    echo "Please source the OpenFOAM/FOAM bashrc first!"
    exit 1
else
    allowed_ver=("v2512" "v2506" "v2412")

    if ! [[ " ${allowed_ver[*]} " == *" $WM_PROJECT_VERSION "* ]]
    then
        echo "WARNING: untested OpenFOAM version '$WM_PROJECT_VERSION'"
        echo "         (supported: ${allowed_ver[*]}) - continuing anyway"
    fi
fi

# Parse arguments for library compilation
if [ -f "$WM_PROJECT_DIR"/wmake/scripts/AllwmakeParseArguments ]
then
    . "$WM_PROJECT_DIR"/wmake/scripts/AllwmakeParseArguments
fi

(
    cd src
    ./Allwmake "$@" 2>&1 | tee log.Allwmake
)

(
    cd applications
    ./Allwmake "$@" 2>&1 | tee log.Allwmake
)

# Check if the build succeeded
echo "Checking if the installation was a success:"
N_ERRORS_1=$({ find . -name log.Allwmake -exec grep -h " Error " {} + || true; } | wc -l)
N_ERRORS_2=$({ find . -name log.Allwmake -exec grep -h " Stop." {} + || true; } | wc -l)

if [[ $N_ERRORS_1 -gt 0 ]] || [[ $N_ERRORS_2 -gt 0 ]]
then
    echo "** BUILD ERROR **"
    echo "There were build errors in the following logs:"
    find . -name log.Allwmake -exec grep -l " Error " {} +
    find . -name log.Allwmake -exec grep -l " Stop." {} +
    echo; echo "Please examine these logs for additional details"; echo
    exit 1
else
    echo
    echo "There were no build errors: enjoy laserHeatFoam!"; echo
fi
echo

#------------------------------------------------------------------------------
