#!/bin/bash
cd "${0%/*}" || exit 1

echo
echo "Cleaning applications"
echo

wclean all solvers
wclean all boundaryConditions

#------------------------------------------------------------------------------
