#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo "Copying 'initial' to 0"
cp -r initial 0

# Create the mesh
runApplication blockMesh

# Run in serial (case is small, ~1600 cells)
runApplication laserHeatFoam
