#!/bin/bash
cd "${0%/*}" || exit 1

targetType=""
optAll="all"

# Parse arguments for library compilation
if [ -f "$WM_PROJECT_DIR"/wmake/scripts/AllwmakeParseArguments ]
then
    . "$WM_PROJECT_DIR"/wmake/scripts/AllwmakeParseArguments
    optAll="-all"
fi

# Recurse into every subdirectory containing a Make/files. Avoids the
# need to keep this script in step with the directory layout.
wmake $optAll $targetType

#------------------------------------------------------------------------------
