#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo "Copying 'initial' to 0"
cp -r initial 0

# Create the mesh
runApplication blockMesh

if [[ $1 == "parallel" ]]
then
    # Run in parallel
    runApplication decomposePar
    runParallel laserHeatFoam
    runApplication reconstructPar
else
    # Run in serial
    runApplication laserHeatFoam
fi